apiVersion: v1
kind: Namespace
metadata:
  name: LocAI
---
apiVersion: v1
kind: Secret
metadata:
  namespace: LocAI
  name: LocAI
type: Opaque
data:
  OPENAI_API_KEY: <base64 encoded key>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: LocAI
  name: LocAI
  labels:
    app: LocAI
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LocAI
  template:
    metadata:
      labels:
        app: LocAI
    spec:
      containers:
        - name: LocAI
          image: <docker user>/LocAI:latest
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: LocAI
                  key: OPENAI_API_KEY
---
kind: Service
apiVersion: v1
metadata:
  namespace: LocAI
  name: LocAI
  labels:
    app: LocAI
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: LocAI
  type: ClusterIP
